# Generated by Django 5.1.3 on 2024-11-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CG', 'Chhattisgarh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HR', 'Haryana'), ('HP', 'Himchal Pradesh'), ('JK', 'JAMMU & KASHMIR'), ('TS', 'Telangana'), ('TN', 'Tamil Nadu'), ('KL', 'Kerala'), ('KA', 'Karnataka'), ('MH', 'Maharashtra'), ('WB', 'West Bengal'), ('MN', 'Manipur'), ('OR', 'Orissa'), ('MP', 'Madhya Pradesh')], max_length=100),
        ),
    ]
